### ISSUE TITLE
Using dependency com.google.gwt:gwt-user:2.8.0 breaks various Xtend validation

### ISSUE THREAD

**Issue by djozis** [xtext/xtext-gradle-plugin#77] opened 2017-02-16 19:37 UTC
Github wouldn't let me upload a zip file of the example project, so I renamed it to gif. Rename it back to zip after downloading or use these snippets from below...
![example](https://cloud.githubusercontent.com/assets/17834241/23037490/9106e63c-f454-11e6-9ad1-03401fb1d9ce.gif)

From my example...
build.gradle:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.xtext:xtext-gradle-plugin:1.0.17'
    }
}

repositories {
    jcenter()
}

apply plugin: 'org.xtext.xtend'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.9.1'
    compile('com.google.gwt:gwt-user:2.8.0') { transitive = false } // Removing this line fixes the problem
}
```
src/main/java/com/example/Example.xtend:
```
package com.example

class Example {
    def example() { class.methods.filter[name == ""] }
}
```

I'm using Gradle 2.13 and Oracle JDK 1.8.0_111.
To reproduce, run: gradle generateXtext
```
>gradle generateXtext
:generateXtext
ERROR:Type mismatch: cannot convert from (Method)=>boolean to Function1<? super Method, Boolean> (file:/.../src/main/java/com/example/Example.xtend line : 4 column : 41)
:generateXtext FAILED
```

Removing the com.google.gwt:gwt-user:2.8.0 dependency causes this validation error not to occur.

(This blocks me from using Gradle/Xtend/GWT together.)
Workarounds appreciated.

**Comment by oehme** [comment] 2017-02-16 20:20
I think this is a duplicate of #54. @svenefftinge is the compiler level for `org.eclipse.xtext.java` configurable now? Last time I checked it was hardcoded to Java 7.

**Comment by cdietrich** [comment] 2017-02-16 20:23
afaik you can install JavaConfig as Adapter to the resourceset

**Comment by px-djozis** [comment] 2017-02-16 20:50
Changing to
```
sourceCompatibility = 1.7
targetCompatibility = 1.7
```
and changing the class to
```
package com.example

import java.lang.reflect.Method
import org.eclipse.xtext.xbase.lib.Functions.Function1

class Example {
    def example() {
        new Function1<Method, Boolean> {
            override apply(Method p) { Boolean.TRUE }
        }
    }
}
```
produces similarly confusing errors
```
>gradle generateXtext
:generateXtext
ERROR:Type mismatch: cannot convert from boolean to Boolean (file:/C:/.../src/main/java/com/example/Example.xtend line : 10 column : 17)
:generateXtext FAILED
```
which again, go away if I comment out the dependency on 'com.google.gwt:gwt-user:2.8.0'.

These examples all compile fine in Eclipse.

What leads you to believe this is Java 8 related? Are you able to provide a modified Gradle script with my example that works, with the dependency on 'com.google.gwt:gwt-user:2.8.0' still in place?

**Comment by oehme** [comment] 2017-02-16 21:07
Can you please try the latest Xtend version first? 2.9.1 definitely had some bugs in type inference.

**Comment by px-djozis** [comment] 2017-02-16 21:23
Switching to 2.10.0 did not solve the issue, but switching to 2.11.0 did solve it.

My real project is a GWT project, and I had issues with 2.11.0.
2.10.0 and earlier worked fine with GWT, but produced this issue.

If you consider upgrading to 2.11.0 to be the resolution to this strange issue when including gwt-user, then I guess I'll open another ticket for the GWT issue once I can pare it down to something worth sharing?

Thanks for your help!

**Comment by oehme** [comment] 2017-02-16 21:39
Yes, please open another issue for the 2.11 problem.

**Closed by oehme** 2017-02-16 21:39 UTC

**Comment by djozis** [comment] 2017-02-17 02:13
Just to follow up, I opened this as the only issue I found at this time for 2.11.0 with GWT: https://github.com/eclipse/xtext-lib/issues/40
