### ISSUE TITLE
DefaultXtextSourceDirectorySet has no outputDir property

### ISSUE THREAD

**Issue by Sandared** [xtext/xtext-gradle-plugin#125] opened 2018-08-11 17:14 UTC
I have an OSGi project that is built with the bnd-gradle plugin where I want to use Xtend as my programming language. When I add the xtend gradle plugin to the project I get a build error complaining about:

`No such property: outputDir for class: org.xtext.gradle.tasks.internal.DefaultXtextSourceDirectorySet`

The [gradle bnd-workspace plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#gradle-plugin-for-workspace-builds) tries to set the `outputDir` property on the `SourceDirectorySet` `"test.java"`  which can be seen [here](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L112)  which seems to lead to the above mentioned error.

I'm not sure if this is an issue for Xtext or bnd, but in the official gradle documentation a `SourceDirectorySet` has the method `setOutputDir(File outputDir)`, so maybe this one should exist also for the `DefaultXtextSourceDirectorySet`?

**Comment by cdietrich** [comment] 2018-08-11 17:27
I have no idea on that. We don’t implement the gradle sourcedirectoryinterface and if we would I have no idea how. Maybe @oehme has some idea or comments on that

**Comment by Sandared** [comment] 2018-08-12 10:46
I created a sample repository [here](https://github.com/Sandared/bnd-xtend-gradle-build)

The gradle `release` task should create a jar in the cnf/release folder. This is where the error occurs.

**Comment by oehme** [comment] 2018-08-23 12:49
The linked line number is off, because the bnd plugin has evolved since the version you are using. The issue is actually in[ this line](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy#L127), which assumes that every language has an `outputDir` property. This is true for java, scala and groovy, but not Xtext. Xtext can have multiple output directories.

The bnd plugin should put a guard in there to check whether such a property actually exists, because it is just a convention, not a hard rule.

**Comment by oehme** [comment] 2018-08-23 12:51
One thing we could do is assume that `setOutputDir` means "set the default outlet". A PR for that would be welcome.

**Comment by oehme** [comment] 2018-08-27 09:03
I thought about the above again and it actually wouldn't make sense, because BND assumes that `outputDir` means "classes go here", which is not true for Xtext (which generates sources). So really this needs to be fixed in the BND plugin. It should explicitly list the languages it wants to support like Scala and Groovy.

**Closed by oehme** 2018-08-27 09:03 UTC

**Comment by Sandared** [comment] 2018-08-28 08:17
Thanks for your work. I will open an issue at bnd.

**Comment by Sandared** [comment] 2018-08-28 14:04
Regarding the answer of BJ Hargrave on [the issue I opened for the bnd-gradle-plugin[(https://github.com/bndtools/bnd/issues/2591): Wouldn't it be sensible to add an additional property `outputDir` to the `DefaultXtextSourceDirectorySet`.
It seems to me that it tries to appear as a `SourceDirectorySet` which, according to the [gradle docs](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html) should have such a property. If Xtend isn't using this property anyway (No class files are created but source files) then there would be no harm in offering this property for any other plugin that wants to interact with the `DefaultXtextSourceDirectorySet` as with any other `SourceDirectorySet` (set the path where to look for class files). I don't have that much experience with gradle, so please correct me if I'm wrong.

WDYT?

**Comment by oehme** [comment] 2018-08-28 18:47
There is no guarantee that every extension on a sourceSet is of type SourceDirectorySet. This just so happens to be true for Java, Groovy and Scala. Other plugins could add any other kind of extension. The bnd plugin shouldn't make assumptions about their type.
