### ISSUE TITLE
Xtend plugin may abort with an error if objects are passed between Xtend and Java

### ISSUE THREAD

**Issue by kirchhof** [xtext/xtext-gradle-plugin#173] opened 2020-07-21 23:33 UTC
## Summary
The Xtend plugin fails in certain cases when passing an object between an Xtend and a Java class. 
This happens when two conditions are met:
1. the class the object was instantiated from was defined in another module, and 
1. the name of the last subpackage of the class starts with an underscore

## Minimal example
Download: [xtendTest.zip](https://github.com/xtext/xtext-gradle-plugin/files/4956932/xtendTest.zip)

The module `module1` includes an Xtend class named `Identifier` and a Java class called `ExampleJavaClass`. The `Identifier` Xtend class calls a method called `uselessTest` that is defined by `ExampleJavaClass`. The `uselessTest` method takes an object of type `Dummy`. `Dummy` is defined by a second module `module2` that is set as a dependency of `module1` in `build.gradle`.

**Expected results**: In this example `gradle build` should  execute without an error.
**Actual results**: The following error occurs:
```
ERROR:The method uselessTest(Object) from the type ExampleJavaClass refers to the missing type Object (file:/<path on my computer>/module1/src/main/java/xtendexample/codegen/Identifier.xtend line : 9 column : 22)
```

If the name of the package of class `Dummy` is changed from `a._b` to `a.b`, the Xtend plugin behaves as expected.

## Possible Workarounds
1. Do not use imported type names in method definitions. Instead, always use the fully qualified name in method definitions.
For example, instead of `public static void uselessTest( Dummy t ) { }` use `public static void uselessTest( a._b.Dummy t ) { }`. You do not need to use the fully qualified name within the method's body.
1. Add a package with the same name as your dependency to the module that uses Xtend. This package has to include at least one dummy class. For example, if you add a class `a._b.XYZ`, then Xtend will also accept the `a._b.Dummy` class from `module2`.

## Other Information
This error does not occur with the Xtend Maven Plugin. It only occurs with the Gradle plugin. Tested with plugin version 2.0.8 and Xtend version 2.22.0.

**Comment by cdietrich** [comment] 2020-07-22 06:39
i assume this is caused by
org.eclipse.xtext.java.resource.IndexAwareNameEnvironment.isPackage(char[][], char[])
which does a Character.isLowercase
(we use the same at other codeplaces too)

**Comment by oehme** [comment] 2020-07-22 06:47
@cdietrich I'll close this issue then. Can you open one for xtext.java?

**Closed by oehme** 2020-07-22 06:47 UTC

**Comment by cdietrich** [comment] 2020-07-22 06:49
created https://github.com/eclipse/xtext/issues/2340

**Comment by kirchhof** [comment] 2020-07-22 06:57
If this is a general Xtext problem, can you tell me why the error only occurs with the Gradle plugin but not with the Maven plugin? I would have expected them both to fail if it was a problem with Xtext.

**Comment by cdietrich** [comment] 2020-07-22 07:04
cause the maven plugin does not make of java source lang
