### ISSUE TITLE
Document (or automate?) advise about how & where to declare all require xtext + xbase dependencies for a lang

### ISSUE THREAD

**Issue by vorburger** [xtext/xtext-gradle-plugin#29] opened 2015-12-11 14:42 UTC
@oehme I'm currently struggling to get xtext-gradle-plugin to work on a sample Xtext language which I've just switched from Xtext 2.8.4 to Xtext 2.9.0 due to dependency errors, and feel some documentation (or perhaps better automation of the required classpath by the xtext-gradle-plugin?) would be of value to end users.

Specifically, I'm trying to cobble this together from https://eclipse.org/Xtext/documentation/350_continuous_integration.html + http://xtext.github.io/xtext-gradle-plugin/xtext-builder.html, and feel something is missing somewhere.

First off, can you confirm that my assumption that the idea here is that until it's possible to build an Xtext lang completely with Gradle (which I understand is not the case as of now), one continues to build the "language" using Tycho as always, but can then use the xtext-gradle-plugin for code generation in the build of runtime projects? So the xtext-gradle-plugin effectively is an alternative for (only) the chapter "Integration in Standard Maven Builds" in the Xtext documentation - right? To test out such a setup, one has to go from `mvn install` in the dir of the lang to `gradlew generateXtext` in the project with `repositories { mavenLocal()` - there is no "smoother" way, right?

Now, where does it get the exact dependencies required to run the code generation from - must a language declare that in the pom.xml (as still Tycho..) of the standalone (non-*.ui) core language bundle, or would you advise to declare it in the build.gradle using the language? Or do you intend the xtext-gradle-plugin to implicitly grab what it needs, based on the Xtext version tag? 

I had started out by declaring nothing, then also tried a `xtext { version = '2.9.0'` in the build.gradle, but first hit: 

```
Execution failed for task ':examples/ch.vorburger.examples.xeemim.pizzas:generateXtext'.
> com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/eclipse/core/runtime/OperationCanceledException```

Then I've added this to the lang's pom.xml:

```
	<dependencies>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.xtext</artifactId>
			<version>${xtext.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.xbase</artifactId>
			<version>${xtext.version}</version>
		</dependency>
	</dependencies>```

only to be greeted by:

```
Execution failed for task ':examples/ch.vorburger.examples.xeemim.pizzas:generateXtext'.
> com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lorg/eclipse/jdt/internal/compiler/batch/CompilationUnit;```

That gets solved by this in the pom.xml:

```
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.core</artifactId>
			<version>3.10.0</version>
		</dependency>
```

only to be greeted from by:

```
Execution failed for task ':examples/ch.vorburger.examples.xeemim.pizzas:generateXtext'.
> ISerializationContext
```

Now this ISerializationContext, which appears to be org.eclipse.xtext.serializer.ISerializationContext (it's funny that the Gradle error does not show the package name?), it cannot find anywhere anymore... I've noticed that there is both a org.eclipse.xtext.xtext:2.9.0 (note the double xtext.xtext) as well as a org.eclipse.xtext:2.9.0 (huh?!), and when I check these JARs in ~/.m2/repository, both appear to contain the .class for org.eclipse.xtext.serializer.ISerializationContext, Gradle does not seem to find it?!

There is also this error:

```Type org.eclipse.xtext.xbase.file.AbstractFileSystemSupport not present```

which is also causing me a test failure in standalone test module, separate from the code generation; it looks like org.eclipse.xtext.xbase.file.AbstractFileSystemSupport was there in 2.8.4 but disappeared in 2.9.0? Not sure what still depends on it...

My Q is: Is this PITA ;-) "normal" and "intended by design" ? Then just close this issue... ;-) But if you meant for this to go a lot smoother, then perhaps some documentation, or more smartness in the gradle plugin, about how to manage dependencies in such a scenario, would be useful to others?

Or maybe you (we?) could extend the https://github.com/xtext/maven-xtext-example to have an example-project-gradle? Let me try that... ;-)

**Comment by oehme** [comment] 2015-12-11 14:54
Hi Michael,

sorry I have no idea what is going on with your language ;) Does it still depend on 2.8 maybe? Because the new plugin will only work with Xtext 2.9+

The Gradle plugin will automatically put Xtext and all it's dependencies on the classpath. It can usually determine the Xtext version automatically if your language has a pom-dependency on Xtext. Alternatively you can explicitly set `xtext.version`. You should not need to do **anything** else yourself.

And yes, this plugin is only meant for "consuming" an Xtext language.

Also, your language should **not** depend on `org.eclipse.xtext.xtext`. That's the Xtext Code Generator (the one you use from mwe) and is not meant to be on your runtime classpath.

Cheers,
Stefan

**Comment by oehme** [comment] 2015-12-11 17:23
I'll close this issue, since the plugin works (as you have seen while creating the herolang example). 

The errors you saw are probably caused by code in your language that depends on Xtext 2.8, which is not supported by the new version of the plugin.

**Closed by oehme** 2015-12-11 17:23 UTC
