### ISSUE TITLE
Gradle problem when refering to Xtext generated class from Xtend

### ISSUE THREAD

**Issue by JanKoehnlein** [xtext/xtext-gradle-plugin#60] opened 2016-08-03 13:26 UTC
Steps to reproduce:
- create a new Xtext project without any extra modules, with Gradle build and Gradle source code layout
- add the following Xtend class

```
package org.xtext.example.mydsl
    
import org.xtext.example.mydsl.services.MyDslGrammarAccess
import com.google.inject.Inject

class Foo {
    @Inject MyDslGrammarAccess grammarAccess
   def foo() {
        grammarAccess.greetingAccess.helloKeyword_0
    }   
}
```

Run ```gradle install```

Results in

ERROR:The method getGreetingAccess() from the type MyDslGrammarAccess refers to the missing type Object (file:/Users/koehnlein/Documents/devel/ride-master/ws/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/src/main/java/org/xtext/example/mydsl/Foo.xtend line : 10 column : 23)
 FAILED

**Comment by cdietrich** [comment] 2016-08-03 14:39
@JanKoehnlein  does this duplicate https://github.com/xtext/xtext-gradle-plugin/issues/55

**Comment by oehme** [comment] 2016-08-03 14:52
It probably does. Can you create a small example project on GitHub?

**Comment by cdietrich** [comment] 2016-08-03 15:56
yes i can

**Comment by cdietrich** [comment] 2016-08-03 16:04
@oehme can be found here https://github.com/cdietrich/xtext-gradle-plugin-issue-60

**Comment by cdietrich** [comment] 2016-08-03 16:23
seems to be a problem in the inc. builder.

adding to XtendIncrementalBuilderTest

```
@Test def void testGrammarAccessproblem() {
		val buildRequest = newBuildRequest [
			dirtyFiles = #[
				'src/mypack/MyFile.xtend' - '''
					package mypack
					
					class Demo {
						
						extension FakeIssue60GrammarAccess
					
						def void format() {
							greetingAccess.helloKeyword_0
						}
						
					}
				''',
				'src/mypack/FakeIssue60GrammarAccess.java' - '''
					public class FakeIssue60GrammarAccess {
						
						private final GreetingElements pGreeting;
						
						public FakeIssue60GrammarAccess() {
							this.pGreeting = new GreetingElements();
						}
						
						public class GreetingElements {
					
							public String getHelloKeyword_0() { return null; }
							
						}
						
						public GreetingElements getGreetingAccess() {
							return pGreeting;
						}
					
					}
				'''
			]
		]
		build(buildRequest)
		assertTrue(issues.toString, issues.isEmpty)
		assertEquals(2, generated.size)
	}
```

gives

```
java.lang.AssertionError: [ERROR:The method getGreetingAccess() from the type FakeIssue60GrammarAccess refers to the missing type Object (inmemory:/src/mypack/MyFile.xtend line : 8 column : 3)]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest.testSimpleMixedBuild2(XtendIncrementalBuilderTest.java:823)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.eclipse.xtext.junit4.XtextRunner$1.evaluate(XtextRunner.java:51)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by cdietrich** [comment] 2016-08-03 16:50
the jvm operation has the type

JvmParameterizedTypeReference:  (type uri: java:/Objects/FakeIssue60GrammarAccess$GreetingElements#FakeIssue60GrammarAccess$GreetingElements)

(coming from org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installFull(Resource))

i dont know if this is ok

**Comment by cdietrich** [comment] 2016-08-03 17:39
the type gets lost in org.eclipse.xtext.xbase.typesystem.internal.AbstractLinkingCandidate.applyToComputationState()

LightweightTypeReference substitutedFeatureType = substitutor.substitute(featureType).getUpperBoundSubstitute();
		if (!expectation.isNoTypeExpectation()) {
			substitutedFeatureType = deferredBindTypeArgument(expectation, substitutedFeatureType);
		}
		expectation.acceptActualType(substitutedFeatureType, ConformanceFlags.UNCHECKED);

**Comment by cdietrich** [comment] 2016-08-03 18:17
org.eclipse.xtext.common.types.access.impl.IndexedJvmTypeAccess.getIndexedJvmType(QualifiedName, String, ResourceSet, boolean) does not handle $ in the fqn

@svenefftinge @JanKoehnlein  what is the intended behaviour here?

**Comment by cdietrich** [comment] 2016-08-03 18:27
org.eclipse.xtext.common.types.xtext.JvmIdentifiableQualifiedNameProvider uses "."
as inner class delimiter.

**Comment by oehme** [comment] 2016-08-03 19:00
@cdietrich Since this is not related to the Gradle plugin, can we close this issue and the duplicate and open one in the Xtext repo?

**Comment by cdietrich** [comment] 2016-08-03 19:08
i think so. will you do that. and link to this issue so that my analysis does not get lost

**Comment by cdietrich** [comment] 2016-08-03 19:20
comparewith org.eclipse.xtext.common.types.impl.JvmIdentifiableElementImplCustom.getQualifiedName()

**Comment by cdietrich** [comment] 2016-08-04 05:13
in jdt the uris look like java:/Objects/demo.Outer#demo.Outer$Inner

**Comment by cdietrich** [comment] 2016-08-05 11:52
@oehme can you close this one and #55 with reference to https://github.com/eclipse/xtext-extras/issues/30

**Comment by oehme** [comment] 2016-08-05 12:30
Thanks for the detailed analysis, @cdietrich :)

**Closed by oehme** 2016-08-05 12:30 UTC
