### ISSUE TITLE
org.xtext.gradle.idea.IdeaDevelopmentPlugin not working with 3.5

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#84] opened 2017-06-08 14:51 UTC
@oehme the org.xtext.gradle.idea.IdeaDevelopmentPlugin (or the config we apply in xtext) does not longer work with gradle 3.5. do you have any idea whats wrong about the config

```
Caused by: java.lang.IllegalStateException: Cannot determine IDEA home directory. Neither 'ideaHome' nor 'ideaVersion' were set.
        at org.xtext.gradle.idea.tasks.IdeaExtension.getIdeaHome(IdeaExtension.java:198)
        at org.xtext.gradle.idea.tasks.IdeaExtension_Decorated.getIdeaHome(Unknown Source)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$2$1.execute(IdeaDevelopmentPlugin.java:145)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$2$1.execute(IdeaDevelopmentPlugin.java:142)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:89)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:78)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 66 more 
```

**Comment by oehme** [comment] 2017-06-08 15:05
Do you have a repro example?

**Comment by cdietrich** [comment] 2017-06-08 15:06
https://github.com/eclipse/xtext-idea/tree/update_gradle

**Comment by cdietrich** [comment] 2017-06-08 15:18
if i understand correct 
ideaDevelopment

should be picked up by 

```
override apply(Project project) {
idea = project.extensions.create(IDEA_DEVELOPMENT_EXTENSION_NAME, IdeaExtension, project)
```

**Comment by cdietrich** [comment] 2017-06-08 19:21
@oehme is it possible that is enhough to rebuild the plugins with gradle 3.5? is the api not backwards compatible so that i can run old plugins without recompile?

**Comment by cdietrich** [comment] 2017-06-09 07:11
@oehme is there a possibility to build a test repo of my branch so that i can consume it from xtext Jenkins?

**Comment by oehme** [comment] 2017-06-09 07:24
> is it possible that is enhough to rebuild the plugins with gradle 3.5? is the api not backwards compatible so that i can run old plugins without recompile?

That's highly unlikely.

> is there a possibility to build a test repo of my branch so that i can consume it from xtext Jenkins?

No, but you can install it locally and then try it out. I may have some time to look at the error later today.

**Comment by cdietrich** [comment] 2017-06-09 07:26
it helped locally but i did a lot of back and forth,
and i dont know what to delete that the plugins will run through their full cycle e.g. downloading

**Comment by oehme** [comment] 2017-06-09 07:39
I was mislead by the exception in the first post, here's the real root cause:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.plugins.ide.api.XmlFileContentMerger.getWhenMerged()Lorg/gradle/listener/ActionBroadcast;
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$10$1.apply(IdeaDevelopmentPlugin.java:404)
```

The other one is just a follow-up, as inidcated by the message `Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.`

`getWhenMerged()` wasn't really intended to be called by clients, but also wasn't clearly marked as internal. It changed in 3.5 and now returns a different type. If we recompile against 3.5, then the plugin will no longer work with older versions. Instead we could call `whenMerged(Closure)`. It's a little more awkward because you have to implement a Groovy closure, but at least it'll work with all Gradle versions.

**Comment by cdietrich** [comment] 2017-06-09 08:01
ok ill have a look

**Comment by cdietrich** [comment] 2017-06-09 08:19
@oehme should a plain stupid action do the same?

```
				file.whenMerged [ Classpath it |
					entries.filter(Library).filter[idea.ideaCoreLibs.contains(library.file)].forEach [
						sourcePath = fileReferenceFactory.fromFile(idea.sourcesZip)
					]
				]
```

**Comment by oehme** [comment] 2017-06-09 08:33
The `Action` overload was only added in 3.5 as well I think (it should have a since tag).

**Comment by cdietrich** [comment] 2017-06-09 09:32
no i mean this one

https://docs.gradle.org/3.3/dsl/org.gradle.plugins.ide.api.FileContentMerger.html#org.gradle.plugins.ide.api.FileContentMerger:whenMerged(org.gradle.api.Action)

**Comment by oehme** [comment] 2017-06-09 13:55
Yeah I thought that one was newer. Glad the fix was so easy then 👍

**Closed by oehme** 2017-06-09 13:55 UTC
