### ISSUE TITLE
Constant merge conflicts due to timestamps in preference files

### ISSUE THREAD

**Issue by dpetroff** [xtext/xtext-gradle-plugin#202] opened 2022-04-04 13:57 UTC
The plugin now generates `org.eclipse.xtend.core.Xtend.prefs` and `org.eclipse.xtext.java.Java.prefs` files with a timestamp, which is updated anytime the Refresh Gradle Project action is triggered in eclipse. This interferes with the ability to use project-specific settings with git.

I need a way to either disable the timestamp which so easily results in 20 changed files and merge conflicts or to specify preferences via the gradle plugin so that the preference files do not need to be tracked. It would also be acceptable for the plugin to never enable the timestamp generation at all, but I think specifying preferences via gradle would be the best option because then the generated preference files do not need to be tracked and new DSL projects under the same gradle parent project can be consistent with the existing ones without manually creating and tracking yet another copy of the same preference files.

**Comment by oehme** [comment] 2022-04-04 14:09
> The plugin now generates

What do you mean by "now"? Is this a recent regression? The plugin uses the Eclipse preference API which is supposed to not have this issue.

> I think specifying preferences via gradle would be the best option

[That already exists.](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/XtextExtension.xtend#L113)

**Comment by dpetroff** [comment] 2022-07-05 13:53
We had recently upgraded from 2.0.8 to 3.0.1 and from gradle 5 to 7.2, which is when the offending files started appearing but I didn't realise 3 years had passed between the last 3 releases of the plugin. The actual gradle tasks don't seem to create the files at all. It's only once the Refresh Gradle Project action is triggered on the parent project in Eclipse that they get (re)created, so it could be a Buildship issue, though the actual `org.eclipse.buildship.core.prefs` file doesn't have a timestamp, unlike the Xtext and Xtend ones.

**Comment by cdietrich** [comment] 2022-07-05 16:27
to me this looks like the EclipsePreferences is somehow bypassed and replaced with a properties.store so that the removeTimestamp is not called. have no idea how to debug this.

**Comment by cdietrich** [comment] 2022-07-05 16:40
@oehme  for some reason stonage old
	 (java.net.URL) jar:file:/Users/cdietrich/.gradle/caches/jars-9/0c337fc3a2b3987cfef0f9ea1d20ec5a/org.eclipse.equinox.preferences-3.4.1.jar!/org/eclipse/core/internal/preferences/EclipsePreferences.class
	 
is used instead of xtexts
api "org.eclipse.platform:org.eclipse.equinox.preferences:3.8.0"

**Comment by cdietrich** [comment] 2022-07-11 11:13
maybe https://github.com/xtext/xtext-gradle-plugin/blob/fb4f60c11315dc0fa584a9933d7fe91ae25d01a9/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtextBuilderPlugin.xtend#L100
also needs some generalization

**Comment by cdietrich** [comment] 2022-07-11 12:08
https://scans.gradle.com/s/zhszalpvpskv4/dependencies?dependencies=pref&expandAll

**Comment by cdietrich** [comment] 2022-07-11 12:18
<img width="525" alt="Bildschirmfoto 2022-07-11 um 14 15 28" src="https://user-images.githubusercontent.com/238736/178262340-6ba8b9d3-98f8-432a-9ecb-9e012548bb93.png">
looks also bogus. why not this one is used:
https://github.com/eclipse/xtext-lib/blob/1ceac635a8f491ae62a17e5a6f17d400d54438be/org.eclipse.xtext.dev-bom/build.gradle#L64

**Comment by oehme** [comment] 2022-07-11 14:30
I'm going to have a look at this this weekend.

**Comment by oehme** [comment] 2022-09-17 10:39
Fixed by https://github.com/xtext/xtext-gradle-plugin/commit/6767e4e4a4acbb0aa75193d6c4b59353edafb99a

**Closed by oehme** 2022-09-17 10:39 UTC
