### ISSUE TITLE
Eclipse .project buildCommand 'org.eclipse.xtext.ui.shared.xtextBuilder' is missing from Gradle generated Eclipse project when using 'org.xtext.android.xtend' plugin

### ISSUE THREAD

**Issue by djozis** [xtext/xtext-gradle-plugin#48] opened 2016-04-02 22:28 UTC
Hopefully I haven't missed something obvious here... sorry if I have!

Versions:
Java 8
com.android.tools.build:gradle:2.0.0-rc1
org.xtext:xtext-android-gradle-plugin:1.0.4

The part where I use these plugins looks like this:
```
	apply plugin: 'android'
	apply plugin: 'org.xtext.android.xtend'
	tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
	eclipseJdt << { file('.settings/org.eclipse.core.resources.prefs').write('eclipse.preferences.version=1\nencoding/<project>=utf-8') }
```
I run 'gradle eclipse' and import the project into Eclipse, but Eclipse never compiles my xtend code. org.eclipse.xtext.ui.shared.xtextBuilder is missing from the .project created.

My current work-around is this:
```
eclipseJdt << { eclipse.project.buildCommand 'org.eclipse.xtext.ui.shared.xtextBuilder'; eclipse.project.buildCommands.with { swap(size - 1, size - 2) } }
```
The swap is to get the new command in before the com.android.ide.eclipse.adt.ApkBuilder buildCommand.

I tried to create a stripped down demo gradle script, but it gave me the opposite behavior - the 'com.android.ide.eclipse.adt.ApkBuilder' buildCommand was missing.

I'm presuming there's some sort of incompatibility going on here?

**Comment by oehme** [comment] 2016-04-04 18:32
The xtext-gradle-plugin adds the Xtext nature and build command. Sounds like some other plugin is overwriting the project configuration. Probably the plugin responsible for doing the ADT config (the official Android build tools don't support Eclipse, so there must be some other plugin in your build that creates ADT configuration).

**Comment by oehme** [comment] 2016-05-01 17:51
Closing since I can't reproduce and there was no further response.

**Closed by oehme** 2016-05-01 17:51 UTC
