### ISSUE TITLE
NullPointerException when generating Xtend

### ISSUE THREAD

**Issue by oxc** [xtext/xtext-gradle-plugin#50] opened 2016-04-08 12:01 UTC
When trying to switch a large multi-project setup from the old xtend-gradle-plugin to the new xtext-gradle-plugin, I'm getting the following NullPointerException during the `generateXtext` task:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installStubs(JavaDerivedStateComputer.java:91)
	at org.eclipse.xtext.java.resource.JavaResource$1.apply(JavaResource.java:125)
	at org.eclipse.xtext.java.resource.JavaResource.initializing(JavaResource.java:146)
	at org.eclipse.xtext.java.resource.JavaResource.installStubs(JavaResource.java:129)
	at org.eclipse.xtext.java.resource.JavaResourceDescriptionManager.getResourceDescription(JavaResourceDescriptionManager.java:47)
	at org.eclipse.xtext.build.Indexer.addToIndex(Indexer.java:356)
	at org.eclipse.xtext.build.Indexer$6.apply(Indexer.java:339)
	at org.eclipse.xtext.build.Indexer$6.apply(Indexer.java:1)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:91)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$2.apply(ClusteringStorageAwareResourceLoader.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterables.addAll(Iterables.java:348)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:95)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:62)
	at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:342)
	at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:238)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:215)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:495)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:476)
	at org.xtext.gradle.builder.XtextGradleBuilder.doBuild(XtextGradleBuilder.java:344)
	at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:228)
	at org.xtext.gradle.tasks.XtextGenerate.build(XtextGenerate.java:359)
	at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:224)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
```

Looks like the JDT Parser returns a null result. Unfortunately, I wasn't yet able to find out which files and/or circumstances are causing this problem. I could not find any useful information in the debug output.

Please let me know what information you require.

This was tested with the following versions:

xtext-gradle-plugin version 1.0.4
gradle version 2.11 and 2.12
xtend version 2.9.2

**Comment by oehme** [comment] 2016-04-08 13:53
If there is some case that org.eclipse.xtext.java cannot handle, it can only be fixed in Xtend itself. Could you please open a bug at the Xtend project at Eclipse?

**Comment by jtandler** [comment] 2016-04-11 13:23
We had the same issue. For us it was related to having *.jar files in resource sourceSets and having them somehow parsed by xtext. Removing those files and adding them later when jar is about to be packaged solved all issues. 

Hopefully this can help other people, too.

**Comment by oehme** [comment] 2016-04-11 13:33
@jtandler do you happen to have a little example project for that? :)

**Comment by remmeier** [comment] 2016-04-27 15:01
I have the same issue, there would be a project here:

https://bitbucket.org/remom/adn_gradle_deltaspike

I can send an invitation if someone would like to have a look. It is a very basic/initial xtend file along a couple of other Java classes in the src/main/java directory. It was working at first, but at some point it stopped. I tried to start using Java classes in Xtend, but not sure if that is related, because I removed it again and it is still not working.

**Comment by remmeier** [comment] 2016-04-29 13:52
at least for my case I found the issue. I had one Java file in the same source directory that was completetly commented out. As a consequence the "types" fields in CompilationUnitDeclaration is null and the for loop crashes:

for (final TypeDeclaration type : result.types) {

**Comment by oehme** [comment] 2016-04-29 13:58
@svenefftinge Can you fix that in org.eclipse.xtext.java? :)

**Comment by oehme** [comment] 2016-05-01 17:50
I'm closing this issue, because it is not caused by this plugin, but by a bug in Xtext itself.

**Closed by oehme** 2016-05-01 17:50 UTC

**Comment by svenefftinge** [comment] 2016-05-01 18:35
see https://github.com/eclipse/xtext/pull/1016
