### ISSUE TITLE
Default methods are not inherited

### ISSUE THREAD

**Issue by oxc** [xtext/xtext-gradle-plugin#54] opened 2016-06-30 17:32 UTC
(I'm not sure if this is a bug in this plugin, but the same code compiles in Eclipse and compiled in the old gradle plugin.)

When a Xtend class implements a (java) interface that contains a default method which is not overridden by the class, the build aborts with an error 

> ERROR:The class TestClass must be defined abstract because it does not implement testMethod()

I thought this might be related to #52, but explicitly setting the javaSourceLevel and/or sourceCompatibilityLevel to 1.8 does not help.

Attached is a minimal example which triggers the issue: [xtend-default-method-issue.zip](https://github.com/xtext/xtext-gradle-plugin/files/342030/xtend-default-method-issue.zip)

**Comment by oehme** [comment] 2016-07-31 19:13
This is caused by the fact that Xtext's standalone Java parser always uses Java 7 source level at the moment. This will be fixed in Xtext 2.11 and incorporated into the plugin as soon as possible.

**Closed** 2021-08-29 08:52 UTC
