### ISSUE TITLE
Build with newer Gradle version

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#107] opened 2018-01-15 08:39 UTC
we should use a newer gradle version to be able to work on machines e.g. with a java 9.0.1 present.
unfortunately there seem to be test errors with that version that i dont understand. see https://github.com/xtext/xtext-gradle-plugin/tree/cd_gradle441

@oehme could you have a look?

**Comment by alcides** [comment] 2018-02-12 11:11
Seconded. I want to migrate to gradle 4.5, and this plugin is preventing me from doing so.

**Comment by oehme** [comment] 2018-02-12 13:23
@cdietrich In Gradle 4.0 we separated the compiler output directory per language (e.g. `build/classes/java/main` instead of just `build/classes/main`). The failed tests are due to wrong assertions (looking for folders which don't exist in 4.0). The plugin should still work though.

While fixing the assertions we should also migrate away from the deprecated `SourceSet#getClassesDir` and instead use `compileJava.destinationDir` [here](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtextBuilderPlugin.xtend#L164). Can you look into that?

@alcides How is the plugin preventing you from migrating? Can you provide a stack trace?

**Comment by cdietrich** [comment] 2018-02-12 13:30
unfortunately i wont find time to work on this the next 2-4 weeks

**Comment by alcides** [comment] 2018-02-12 13:38
Context: This is a project that parses a specification language and makes SMT verifications. We are using gradle as our build tool, and requires XText passes to generate Java sources. 

Our relevant gradle config:

`
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.xtext:xtext-gradle-plugin:1.0.15'
        classpath 'org.xtext:xtext-idea-gradle-plugin:1.0.15'
    }
}

configure(subprojects.findAll { it.name.startsWith('rsl') }) {
	ext.xtextVersion = '2.13.0'
	repositories {
		jcenter()
	}
	
	apply plugin: 'java'
	apply plugin: 'org.xtext.xtend'
	apply from: "${rootDir}/gradle/source-layout.gradle"
	apply from: "${rootDir}/gradle/maven-deployment.gradle"
	apply plugin: 'eclipse'
	apply plugin: 'idea'
	
	group = 'rsl'
	
	sourceCompatibility = '1.8'
	targetCompatibility = '1.8'
	
	configurations.all {
		exclude group: 'asm'
		resolutionStrategy {
//			failOnVersionConflict()
			
			force 'org.eclipse.xtend:org.eclipse.xtend.lib:2.13.0'
			force 'log4j:log4j:1.2.16'
			force 'com.google.guava:guava:19.0'
			force 'org.slf4j:slf4j-api:1.7.21'
			force 'junit:junit:4.12'
			force 'com.google.code.gson:gson:2.7'
            force 'commons-io:commons-io:2.5'
            force 'joda-time:joda-time:2.9.4'
		}
	}
}
`

Here is the exception that stops the build:

`Caused by: java.lang.NoSuchMethodError: org.gradle.plugins.ide.api.XmlFileContentMerger.getWhenMerged()Lorg/gradle/listener/ActionBroadcast;
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$10$1.apply(IdeaDevelopmentPlugin.java:404)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$10$1.apply(IdeaDevelopmentPlugin.java:397)
        at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$10.execute(IdeaDevelopmentPlugin.java:434)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$10.execute(IdeaDevelopmentPlugin.java:386)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin.addIdeaDependenciesToEclipseClasspath(IdeaDevelopmentPlugin.java:437)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin.access$400(IdeaDevelopmentPlugin.java:68)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$6$1.execute(IdeaDevelopmentPlugin.java:308)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$6$1.execute(IdeaDevelopmentPlugin.java:304)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$6.execute(IdeaDevelopmentPlugin.java:313)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin$6.execute(IdeaDevelopmentPlugin.java:297)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin.integrateWithJavaPlugin(IdeaDevelopmentPlugin.java:316)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin.apply(IdeaDevelopmentPlugin.java:131)
        at org.xtext.gradle.idea.IdeaDevelopmentPlugin.apply(IdeaDevelopmentPlugin.java:67)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:129)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:130)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:114)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:38)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:77)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:40)
        at org.xtext.gradle.idea.IdeaPluginPlugin.apply(IdeaPluginPlugin.java:43)
        at org.xtext.gradle.idea.IdeaPluginPlugin.apply(IdeaPluginPlugin.java:28)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_5sv3jytqiqpisjf26wliz6jql.run(/Users/alcides/Code/Research/RestSpecificationLanguage/software/rsl.idea/build.gradle:2)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 93 more
`

**Comment by oehme** [comment] 2018-03-15 14:32
@alcides You are using an outdated version of the plugin, that bug has long been fixed.

**Comment by cdietrich** [comment] 2018-03-30 13:41
@oehme i gave it a try on https://github.com/xtext/xtext-gradle-plugin/tree/cd_issue107

unfortunately BuildingAPlainLanguageProject.generateOnceFoldersAreNotCleanedByCleanBuilds.
fails. do you have any hint why. there are two places like `.filter[cleanAutomatically]` in `XtextBuilderPlugin` and `XtextGradleBuilder`. But they dont/no longer seem to be responsible for that.

**Comment by oehme** [comment] 2018-04-03 05:53
I'm afraid this is Gradle's stale output cleanup doing its job. Whenever there is no history of the task (which is the case here since it is the first build), we delete that task's output.  

"generate once" kinda bends the concept of an "output". We could remove this folders from the [declared outputs](https://github.com/xtext/xtext-gradle-plugin/blob/cd_issue107/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/XtextGenerate.xtend#L67) completely. We'd then be sneakily generating things into an undeclared location. I guess that's the only way to make "generate once" work. 

This disqualifies any language using "generate once" from using the build cache.

**Comment by cdietrich** [comment] 2018-05-29 13:48
@oehme one general question:

how does the gradle version of the plugin and the gradle version of the build using the plugin play together compatibility wise?

**Comment by oehme** [comment] 2018-05-29 14:21
They are completely independent. However, compling against a newer Gradle API can lead to accidentally calling methods that are not there on older versions. That's why cross-version coverage is important, especially if you want to build the plugin with a newer version than the minimum you want to be compatible with.

**Comment by ArneDeutsch** [comment] 2018-05-29 14:38
The commits from Christian were not merged. Have you just stopped implementing or are there other reasons?

**Comment by cdietrich** [comment] 2018-05-29 14:40
i did no find the time to finish it. e.g. tests are missing

**Comment by ArneDeutsch** [comment] 2018-06-06 13:50
I have upgraded the used gradle to 4.3. With the PR we are backwards compatible to this version. Reason: Inside gradle 4.3 the "bootClasspath" was deprecated in favor of "bootstrapClasspath". Using the new variable makes the plugin incompatible with grave <4.3. Hence with new plugin version supports all gradle versions from 4.3 to 4.8 (inclusive).

**Comment by ArneDeutsch** [comment] 2018-06-08 05:50
Latest comit should be good. Have added some test cases and filtered the OutputConfigurations such that all tests pass. I agree that we should lift major version number because we are no more compatible with gradle 3.x after the update. But that is probably other ticket.

**Comment by oehme** [comment] 2018-08-23 12:57
This was fixed by #117

**Closed by oehme** 2018-08-23 12:57 UTC
