### ISSUE TITLE
Class shadowing does not work

### ISSUE THREAD

**Issue by CharmsStyler** [xtext/xtext-gradle-plugin#91] opened 2017-08-04 12:43 UTC
The below scenario works in Eclipse as it honors  inline project class A. However when built with gradle it fails as it still refers the upstream project A. Please see the stacktrace below. 

Attached a sample use case test to BuildingAMultiModuleXtendProject as follows
```

	@Test
	def void samePackageClassNameInUpStreamAndDownStream() {
		val upStream = upStreamProject.createFile("src/main/java/A.java", '''public class A {}''')
		val downStreamA = downStreamProject.createFile("src/main/java/A.java", '''public class A { public static String Hello() { return "downStreamProjectA"; } }''')
		val downStream = downStreamProject.createFile("src/main/java/B.xtend", '''class B {
			def static void main(String[] args) {
				println(A.Hello)
			}
		}
		''')
		build("build")
	}
```

Attaching the exception stacktrace
```
samePackageClassNameInUpStreamAndDownStream

org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /var/folders/qs/bctcgc5n40x4hhdwtt51nf5c0000gn/T/junit4100557352248016253/root with arguments [build]

Output:
:upStream:generateXtext UP-TO-DATE
:upStream:compileJava
:upStream:processResources UP-TO-DATE
:upStream:classes
:upStream:jar
:downStream:generateXtextERROR:The method or field Hello is undefined for the type Class<A> (file:/private/var/folders/qs/bctcgc5n40x4hhdwtt51nf5c0000gn/T/junit4100557352248016253/root/downStream/src/main/java/B.xtend line : 3 column : 15)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downStream:generateXtext'.
> Xtext validation failed, see build log for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.417 secs

	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:222)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:219)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:282)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:219)
	at org.xtext.gradle.test.GradleBuildTester.build(GradleBuildTester.java:160)
	at org.xtext.gradle.test.BuildingAMultiModuleXtendProject.sameClassSharedInupStreamAndDownStream(BuildingAMultiModuleXtendProject.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by oehme** [comment] 2017-08-04 13:18
I'm not sure whether this is an issue with the plugin, since it just passes the classpath and sourcepath to Xtext. It might be an issue in Xtext's incremental builder. Can you see if you can reproduce the same issue in the incremental builder test of [Xtend](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend)?

**Comment by CharmsStyler** [comment] 2017-08-05 06:24
@oehme It works in **XtendIncrementalBuilderTest**  However I am not sure if it's the proper way to that I have setup the Class A for this. 

```

	@Test def void testSameClassOnDifferentProjects() {
		val buildRequest = newBuildRequest [
			dirtyFiles = #[
				'src/mypack/A.java' - '''
					package mypack;
					public class A {  
					}
					
				'''
			]
		]
		build(buildRequest)

		assertTrue(issues.toString, issues.isEmpty)

		val buildRequest2 = newBuildRequest [
			dirtyFiles = #[
				'src/mypack/A.java' - '''
					package mypack;
					public class A { public static String Hello() { return "downStreamProjectA"; } }
					
				''',
				'src/mypack/Demo.xtend' - '''
					package mypack
					class Demo {
								def static void main(String[] args) {
									println(A.Hello)
							}
					}
				'''
			]
		]
		build(buildRequest2)
		assertTrue(issues.toString, issues.isEmpty)
	}
```

**Comment by oehme** [comment] 2017-08-05 06:49
The code above doesn't create any connection between the two build requests, it just builds both in isolation.

It seems there are no tests for classpath integration on that class, so you might have some

**Comment by oehme** [comment] 2017-08-05 06:49
The code above doesn't create any connection between the two build requests, it just builds both in isolation.

It seems there are no tests for classpath integration on that class, so you might have some

**Comment by svenefftinge** [comment] 2017-08-07 12:32
Coming back from vacation I have a longer backlog :|. 
But AFAIR we are relying on a classloader, that has the inverse shadowing semantics (i.e. prefers upstream). Maybe that's the issue here? I personally try to avoid utilizing class shadowing :)

**Comment by svenefftinge** [comment] 2017-08-07 12:35
That said, the classes should be looked up from the index. Sorry, I would have to actually go and read/debug that code, but that is not possible atm.

**Comment by CharmsStyler** [comment] 2017-08-08 14:42
@svenefftinge is it different when used within eclipse ? class shadowing only becomes an issue when built with gradle.

**Comment by svenefftinge** [comment] 2017-08-09 05:55
Yes, in eclipse we use JDT to look up types.

**Comment by cdietrich** [comment] 2017-08-09 06:58
@svenefftinge i tried to analyze this. during the build in my example `/Users/dietrich/xtext-dev/runtime-EclipseXtext/org.xtext.example.mydsl3.parent/org.xtext.example.mydsl3.ide/src/main/java/org/xtext/example/mydsl3/A.java#org.xtext.example.mydsl3.A` is found by the indexed access which is correct. do you have an idea where lateron this one could be switched out?

**Comment by cdietrich** [comment] 2017-08-09 07:19
the linked resource is even the 

org.eclipse.xtext.java.resource.JavaResource@69fc75f3 uri='file:/Users/dietrich/xtext-dev/runtime-EclipseXtext/org.xtext.example.mydsl3.parent/org.xtext.example.mydsl3.ide/src/main/java/org/xtext/example/mydsl3/A.java'

=> i wonder why there is no overriden method found

**Comment by cdietrich** [comment] 2017-08-09 07:26
is it possible that 

org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installFull(Resource)

does not do what it should?

**Comment by cdietrich** [comment] 2017-08-09 08:46
@oehme @svenefftinge  if found the issue. its a bug in java source lang. will file a bug

**Comment by oehme** [comment] 2017-08-09 09:56
Thanks a lot @cdietrich! I'll close this one then.

**Closed by oehme** 2017-08-09 09:56 UTC

**Comment by cdietrich** [comment] 2017-08-09 12:46
@CharmsStyler you should be able to test the fix with Xtext Version 2.13.0-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots

**Comment by gihanmaduranga** [comment] 2017-08-14 07:44
@cdietrich seems like 2.13.0-SNAPSHOT artifact is not deployed to the following repo https://oss.sonatype.org/content/repositories/snapshots/

here is the code snippet in gradle build script 
`    
buildscript {
 repositories {
 maven {
 url "https://oss.sonatype.org/content/repositories/snapshots/"
 }
 }
 dependencies {
 classpath "org.xtext:xtext-gradle-plugin:2.13.0-SNAPSHOT"
 }
 }`
Please have a look.thanks.

**Comment by cdietrich** [comment] 2017-08-14 07:47
?????

https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.java/2.13.0-SNAPSHOT/

**Comment by cdietrich** [comment] 2017-08-14 07:48
the xtext gradle plugin stays the same. you need to change the version of xtext itself
